repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.26
    hooks:
      - id: uv-lock # ensure the lockfile is up-to-date
      - id: uv-export #autoexport uv.lock to requirements.txt
      - id: pip-compile # Compile requirements
        args: [requirements.txt]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.6"
    hooks:
      - id: ruff
        args: [--fix, --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
